server:
  port: 8886
info:
  api-doc: /swagger-ui.html
spring:
  application:
    name: ycdemo
  profiles:
    active: test
---
spring.profiles: test
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&autoReconnect=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 500
    initialSize: 20
    maxWait: 60000
    minIdle: 50
    maxIdle: 500
    timeBetweenEvictionRunsMillis:  60000
    minEvictableIdleTimeMillis:  300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow:  false
    testOnReturn: false
    poolPreparedStatements: false
    maxOpenPreparedStatements:  20
    removeAbandoned : false
    maxPoolPreparedStatementPerConnectionSize : 50
    dialect: MYSQL


mybatis:
  type-aliases-package: com.yc.demo.domain
  mapper-locations: classpath:mapper/*.xml

logging:
  level.com.yc.demo.mapper: debug
  # 当前项目生成指定日志名的日志文件，文件名前添加完整路径，则在指定路径下生成日志
#  file:
  # 指定路径，则在该路径下生成默认名称为 spring.log 的日志文件
#  path:
  # 指定日志输出的等级 trace<debug<info<warn<error，默认级别为 info

---
spring.profiles: prod
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&autoReconnect=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 500
    initialSize: 20
    maxWait: 60000
    minIdle: 50
    maxIdle: 500
    timeBetweenEvictionRunsMillis:  60000
    minEvictableIdleTimeMillis:  300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow:  false
    testOnReturn: false
    poolPreparedStatements: false
    maxOpenPreparedStatements:  20
    removeAbandoned : false
    maxPoolPreparedStatementPerConnectionSize : 50
    dialect: MYSQL

mybatis:
  type-aliases-package: com.yc.demo.domain
  mapper-locations: classpath:mapper/*.xml

logging:
  level.com.yc.demo.mapper: debug
  # 当前项目生成指定日志名的日志文件，文件名前添加完整路径，则在指定路径下生成日志
#  file:
  # 指定路径，则在该路径下生成默认名称为 spring.log 的日志文件
#  path:
  # 指定日志输出的等级 trace<debug<info<warn<error，默认级别为 info
